version: '3.1'

services:

  wordpress:
    build:
      context: ./php5.6
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - /mnt/wsl/PhysicalDrive4p2/wejob-wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: wjroot
    volumes:
      - /mnt/wsl/PhysicalDrive4p2/wejob-wpdb:/var/lib/mysql

